### ISSUE TITLE
ActionBarCompat (ABC) support available ?

### ISSUE THREAD

**Issue by LOG-TAG** [dgmltn/Android-ShareEverywhere#1]
I'm looking for ABC support , Many of the developers Started migrating from ABS to ABC so I feel ABC support is more trending now days!

**Comment by dgmltn** [comment]
All you should have to do for ABC support is to swap a couple imports with their ABC equivalents (*.Menu, *.MenuItem, *.SubMenu, and *.ActionProvider in ShareActionProvider.java and ShareView.java. Let me know how it works for you, and I'll update the documentation.
